-   hosts: windows #all
    
    vars:
        software:
            # DESASTRE GIGANTE !!!!! MIERDA MAGNA !
            - nombre: apache
              ruta_instalador: //servidor17/caprtasoftware/software3
              url_instalador: http://.......instalador.exe
              # Repo git con el fichero config
              configuracion: http://.......configuracion.conf
              argumentos_instalador: []
              puertos:
                - 80
                - 443


    pre_tasks:
        -   name: Asegurarme que hay unas carpetas temporales donde ubicar recursos necesarios
            block:
                -   name: Carpeta temporal base
                    #debug:
                    #    msg: Asegurando que existe carpeta temporal
                    win_file:
                        path: c:\temporal
                        state: directory

                -   name: Asegurando que existe carpeta para cada software
                    #debug:
                    #    msg: "Creando carpeta del software: {{ item.nombre }}"
                    win_file:
                        path: "c:\\temporal\\{{ item.nombre }}"
                        state: directory

                    loop: "{{ software }}"
            tags:
                - preparacion
                    
        -   name: Asegurarme que tengo los programas de instalación
            block:
                -   name: Descargar los programas de instalación que sean descargables
                    debug:
                        msg: "Descarga software {{ item.url_instalador }}"
                    when: item.url_instalador is defined
                    loop: "{{ software }}"
                  
                -   name: Traerme de un entorno de mi red un programas de instalación que ya hubiera conseguido por algún medio
                    debug:
                        msg: "Copiar software {{ item.ruta_instalador }}"
                    when: item.ruta_instalador is defined
                    loop: "{{ software }}"
            tags:
                - preparacion
    
        # Acabo con unos ejecutables en una carpeta: c:\windows\temp
        -   name: Hacerme con las configuraciones
            block:
                -   name: Descargar configuraciones de un scm
                    debug:
                        msg: "Obtener configuraciones {{ item.configuracion }}"
                    when: item.configuracion is defined
                    loop: "{{ software }}" # lista de valores... de donde la sacas
            tags:
                - preparacion
    
        # Acabo con unas configuraciones en una carpeta: c:\windows\temp
    tasks:
        - name: Asegurar que el software queda instalado en la máquina
          debug:
            msg: |
                Asegurar presencia de  {{ item.nombre }}
                Configuración del instalador {{ item.argumentos_instalador }}
          loop: "{{ software }}"
          tags:
            - instalacion
        # En la medida de lo posible NUNCA JAMAS NUNCA JAMAS DE LOS JAMASES EJECUTO UN COMANDO.... NUNCA !!!!
        
        # Siempre quiero ejecutar el instalador?
        # "Ejecutar instalador" es el nombre que NUNCA JAMAS DE LOS JAMASE MAS QUE LOS DE ARRIBA DE LOS JAMAS MAS NUNCA LO PONDRIA 
        # En que caso no? Si ya está instalado.
        
        - name: Asegurar que hay la configuración adecuada
          debug:
            msg: Configuración del software {{ item.configuracion }}
          loop: "{{ software }}"
          tags:
            - configuracion
          notify: CAMBIO_CONFIGURACION_SERVICIO
        
        - name: Asegurar que hay un servicio creado y configurado
          debug:
            msg: Asegurar servicio {{ item.nombre }}
          loop: "{{ software }}"
          tags:
            - configuracion
        
        - name: Asegurar que los puertos queden abiertos
          debug:
            msg: Asegurar puerto {{ item.1 }} para el programa {{ item.0.nombre }}
        # modulo... que hará la copia a la ubicacion correcta... pero entre medias... sustituirá algunos parametros
            # Cómo me refiero a un puerto????
            # Puerto: item[1]             item.1
            # Nombre: item[0].nombre      item.0.nombre
            
          loop: "{{ software | subelements('puertos') }}"
          tags:
            - configuracion
        
        

    post_tasks:
        -   name: Asegurar que el servicio queda iniciado
            debug:
                msg: Asegurar servicio iniciado {{ item.nombre }}
            # modulo... que hará la copia a la ubicacion correcta... pero entre medias... sustituirá algunos parametros
            loop: "{{ software }}"
            tags:
            - configuracion

        -   name: Borrar carpetas si existen
            debug:
                msg: Borrar carpeta raiz
            tags:
                - limpieza    

        -   name: Smoke Test
            block:
                -   name: Comprobar servicios
                    debug:
                        msg: Comprobar servicio iniciado {{ item.nombre }}
                    loop: "{{ software }}"
            tags:
                - tests
        
    
    
    handlers:
        - name: Reiniciar Servicio
          debug:
                msg: Reiniciar servicio {{ item.nombre }}
          loop: "{{ software }}"
          tags:
            - configuracion
          listen:
            - CAMBIO_CONFIGURACION_SERVICIO
        


#######
#.       $ ansible-playbook -i inventario.??? --skip-tags="preparacion,limpieza"  playbook.yaml #.       
#.       $ ansible-playbook -i inventario.??? --tags="instalacion"  playbook.yaml 

