-   hosts: all
    
    gather_facts: false
    
    pre_tasks:
        - name: Identificar Sistema Operativo
          include_tasks: "tasks/pre_tasks_os.yaml"

        - name: Descargas y preparaciones
          include_tasks: "tasks/pre_tasks.yaml"
          when: ansible_facts.os_family == 'Windows'

    tasks:
        - name: Instalaciones y configuraciones adicionales
          include_tasks: "tasks/tasks.yaml"
          when: ansible_facts.os_family == 'Windows'

    post_tasks:
        - name: Comprobaciones y tareas adicionales
          include_tasks: "tasks/post_tasks.yaml"
          when: ansible_facts.os_family == 'Windows'

    handlers:
        - name: Reiniciar Servicio
          win_service:
                name: "{{ item.nombre }}"
                state: restarted
          loop: "{{ software }}"
          tags:
            - configuracion
          listen:
            - CAMBIO_CONFIGURACION_SERVICIO


#######
#.       $ ansible-playbook -i inventario.??? --skip-tags="preparacion,limpieza"  playbook.yaml #.       
#.       $ ansible-playbook -i inventario.??? --tags="instalacion"  playbook.yaml 
# ansible-playbook -i inventarios/windows.ini -e "@ejercicios/vars.mysql.yaml" ejercicios/instalador.guay/playbook.yaml 
