- # PLAY: 'Programa': Un estado en el quiero encontrar un entorno remoto
    # vamos a tener un fichero de inventario. 
    # Esta marca limita dentro de ese inventario donde puedo ejecutar el playbook.
    # Este no es el único sitio donde establecer esta limitación.
    # Es mucho más frecuente, esa limitación hacerla en tiempo de ejecución.
    # Así es más flexible.
    hosts: localhost        # Entornos en los que poder ejecutar este play
                            # Una práctica habitual es poner:
                            # - "all": Todos los del inventario
                            # - nombre de host: "localhost", "mipc17", "bbdd.produccion.es"
                            # - rango de maquinas: "bbdd1.produccion.es:bbdd9.produccion.es"
                            # - grupo: Los hosts, en los inventarios, los podré clasificar en grupos.
                            #   "produccion"
                            #   "servidores-web"
                            # - Combinaciones de grupos
                            #   "servidores-web:&produccion" Los servidores web de producción
                            #   "servidores-web:!produccion" Los servidores web de no son de producción
    
    # Al ejecutarse sobre 25 servidores... Como funciona eso? 
    # Se va de 1 en 1 o cómo? Depende cómo configure la ejecución.
    # Definiremos un tamaño de pool de ejecutores: Cuantos en paralelo: 7
    # Y en que orden se van procesando? Da igual?
    # Me temo que on... Hay muchos escenarios donde NO DA IGUAL:
    # SQL Server Activo / Replica:
    # 1º Activo.   actualiza a la nueva versión
    #                VVV
    # 2º Replica.  actualiza a la nueva versión
    
    # Activo/Pasivo: H/A
    # IIS Maquina 1 - Running
    # IIS Maquina 2 - Pasivo - StandBy

    # Actualizo el standby tranquilidad... Si se jode no pasa nada... no corto servicio
    # Cambio... y ya actualizo el que era activo
    order: inventory            # Según el orden del inventario
         # sorted               # Orden alfabético 
         # reversed_sorted      # Orden alfabético descendente
         # reversed_inventory   # Orden del inventario invertido 
         # shuffle              # Orden aleatorio

    gather_facts: True 
                 #False     # Desactivo completamente que se lean datos del entorno remoto
                            # Por defecto, Ansible se trae un huevon de datos del remoto.
                            # En la práctica no quiero NI LO UNO NI LO OTRO.

    vars:                   # Definir variables para su uso dentro del playbook
                            # Parametros, configuraciones personalizables que puedo hacer sobre los plays
        mi_variable1: VALOR1
        mi_variable2: VALOR2
        instalar:   false

    pre_tasks:
        -   name: Pretarea 1
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Soy la PREtarea 1... y me estoy ejecutando.

    tasks:                  # QUITAR LA PALABRA TASK DE VUESTRO CEREBRO. Aqui la tengo que poner
                            # Definir los ESTADOS ddeseados.
#        -   name:
#            tipo:  # Corresponde con un MODULO DE ANSIBLE
#                parametrizacion...
        -   name: Tarea 1
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Soy la tarea 1... y me estoy ejecutando.
                
#            ejecutar-script-powershell...
#            Que sabe el modulo de si aquello ha realizado cambios?

        -   name: Tarea 2 - Mostrar las ips recopiladas de la máquina
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                var: ansible_facts.all_ipv4_addresses
            
        -   name: Tarea 3 - Mostrar variable 1
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                var: mi_variable1
            
        -   name: Tarea 4 - Mostrar variable 2
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                var: mi_variable2

        -   name: Tarea 5 - Mostrar variable 2... con una redefinición
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                var: mi_variable2.clave2[0]
            vars:
                mi_variable2: 
                    clave1: 33
                    clave2:
                        - item1
                        - True

        -   name: Tarea 6 - Mostrar variable 2
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                var: mi_variable2

        # Logica al playbook
        
        # Condicionales
        -   name: Tarea 7 - Mostrar un mensaje solo si hay que instalar
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Vamos a instalar !!!!!!
            when:    instalar
            #when:   instalar == true
            
            # En cualquier condicion:
            # - when
            # - changed_when
            # - failed_when
            # Podeis usar los operadores: > < >= <= != ==
            # 'is search'
            # Expresiones del tipo: 
            #       variable_que_contiene_texto is search('REGEX')
            #       variable_que_contiene_texto is search('ERROR|Error|error')
            #
            # En estas de abajo no podeis usar regex:
            #       'ERROR' in variable_que_contiene_texto
            #       'ERROR' not in variable_que_contiene_texto
            
            # De una variable siempre podreis pedir:
            # mivariable is defined
            # mivariable is undefined
            # mivariable is not defined
            # mivariable is not undefined

            
        -   name: Tarea 8 - Cambiar el fichero de configuracíon A
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Cambiando el fichero A.....
            # Expresión lógica (IF) para determinar si esta tarea debe considerarse que ha provocado un cambio
            changed_when: true #
            # La tarea que notificamos SOLO ES ACTIVADA si esta tarea.. 
            # la que estoy definiendo en estas lineas.... TAREA 8
            # Provoca un CAMBIO : CHANGED
            notify: Tarea B - REINICIO DEL SISTEMA
                
        -   name: Tarea 9 - Cambiar el fichero de configuracíon B
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Cambiando el fichero B.....
            changed_when: true #
            # En este caso, si esta tarea provoca un cambio (changed),
            # Se notifica un EVENTO, lo que implica que TODAS LAS TAREAS
            # Que escuchan el evento, se ejecutan.
            notify: CAMBIO-CONFIGURACION 

        -   meta: flush_handlers        # Fuerza la ejecución de los handlers que hayan sido activados
                                        # en este momento de la ejecución

        -   name: Tarea 10 - Otras cosas que hay que hacer....
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Muchas cosas
            # Expresión lógica (IF) para determinar si esta tarea debe considerarse que ha provocado un fallo
            failed_when: false #

    post_tasks:
        -   name: Posttarea 1
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Soy la Posttarea 1... y me estoy ejecutando.
        
        # Bucles
        -   name: Tarea que se ejecuta en bucle
            debug:
                msg: |-
                    Soy la tarea que abre puertos del firewall de windows.
                    Voy a abrir el puerto: {{ item }}
                # Concepto de interpolación: Reemplazar una variable dentro de un texto por su valor.
                # Nos ayuda un placeholder de jinja {{ nombre_variable }}
                # realmente jinja permite ahí dentro poner:
                # - Funciones   {{ nombre-funcion(variable) }}
                # - Filtros:    {{ variable | nombre-filtro }}
                #    {{ texto | default('valor por defecto') }} 
                #    {{ texto | upper }} Pone el valor de la variable texto en MAYUSCULAS
                #    {{ texto | lower }} 
                #    {{ texto | capitalize }} 
                #    {{ texto | title }} 
                #    {{ texto | trim }}  Comote espacios en blanco por delante y detrás
                
                #  {{ lista | first }}
                #  {{ lista | sum }}
                #  {{ lista | last }}
                #  {{ lista | length }}
                #  {{ lista | max }}
                #  {{ lista | min }}
                #  Listado de filtro jinja: https://jinja.palletsprojects.com/en/3.1.x/templates/#builtin-filters
                    
                    
                    
            loop: "{{ puertos }}"
            vars:
                puertos: #[80, 8080, 8443]
                    - 80
                    - 8080
                    - 8443
                    
        -   name: Ejecutar script
            #win_shell: |
            shell: |
                echo HOLA
                ls -l
            register: SALIDA_SCRIPT

        -   name: Ver salida script
            debug:
                msg: |
                    Codigo salida: {{ SALIDA_SCRIPT.rc }}
                    Comando: {{ SALIDA_SCRIPT.cmd }}
                    stdout: {{ SALIDA_SCRIPT.stdout }}

        # Bucles
        -   name: Tarea que se ejecuta en bucle
            shell: |
                  echo PUERTO: {{ item }}
            loop: "{{ puertos }}"
            # Los bucles antiguamente se hacían con otro tipo de palabras en ansible.
            # with_
            # Los with_ están deprecated...
            
            # Hay muchos tipos de bucles y algunos complejos. Antes existian muchas funciones WITH 
            # para cada tipo de bucle... Hoy en dia, hay funciones JINJA para ello.
            
            # Mirar tipos de bucle en: 
            # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#id21
            
            
            # Tipos de bucles:
            # - SENCILLO: me dan una lista y recorro sus valores, 
            #             haciendo la tarea para cada uno de los valores de la lista.
            # - ITERA DOS LISTAS A LA VEZ . zip
            #       [1,2,3][A,B,C]
            #            iteracion 1: 1,A
            #            iteracion 2: 2,B
            #            iteracion 3: 3,C
            # - MULTIPLICAR DOS LISTAS ENTRE SI: Producto Cartesiano
            #       [1,2,3][A,B,C]
            #           iteracion 1, A
            #           iteracion 1, B
            #           iteracion 1, C
            #           iteracion 2, A
            #           iteracion 2, B
            #           iteracion 2, C
            #           iteracion 3, A
            #           iteracion 3, B
            #           iteracion 3, C
            # - ITERAR CADA ELEMENTO DE UNA LISTA CON UN SUBELEMENTO
            #       [
            #            - servicio: http
            #              puertos:
            #                - 80
            #                - 8080
            #            - servicio: https
            #              puertos: 
            #                - 443
            #                - 8443
            #       ]
            #               iteracion 1: http - 80
            #               iteracion 2: http - 8080
            #               iteracion 3: https - 443
            #               iteracion 4: https - 8443
            vars:
                puertos: #[80, 8080, 8443]
                    - 80
                    - 8080
                    - 8443
            register: SALIDA_PROGRAMA_PUERTOS
            # Qué se guarda dentro de la variable registrada? SALIDA_PROGRAMA_PUERTOS?
            # Los datos que nos diga el módulo en su documentación que se ofrecen como datos de salida

            # Con independencia del módulo que se haya ejecutado en la tarea 
            # de la que hemos hecho un register, siempre podremos consultar:
            # SALIDA_PROGRAMA_PUERTOS is failed
            # SALIDA_PROGRAMA_PUERTOS is succeded
            # SALIDA_PROGRAMA_PUERTOS is changed
            # SALIDA_PROGRAMA_PUERTOS is skipped


        -   name: Ver salida script
            debug:
                var: SALIDA_PROGRAMA_PUERTOS.results[1].stdout

        # Control de errores
        
        -   name: Hago copia de seguridad
            debug:
                msg: Hago copia de seguridad
                
        -   name: Nombre del bloque
            block:
                -   name: Tarea delicada, que puede fallar
                    shell: exit 1
            rescue: # Pondremos tareas que queremos ejecutar si alguna de las tareas del bloque ha fallado
                -   name: Restauro copia de seguridad
                    debug:
                        msg: Restauro copia de seguridad
            always: # Pondremos tareas que queremos ejecutar siempre, con independencia de si alguna tarea falló
                -   name: Borrar copia de seguridad
                    debug:
                        msg: Borrar copia de seguridad
            #vars:
            #when: CONDICION
        -   name: Una tarea ETIQUETADA
            debug:
                msg: Hola, me ejecuto
            tags:
                - instalacion
                - test
                - configuracion
                - backup
            # El haber definido tags, nos permite posteriormente solicitar la ejecución SOLO DE las tareas
            # CON UN DETERMINADO TAG den un playbook...
            # O lo contrario: SOLO LAS TAREAS que NO TENGAN UN TAG (excluya un tag)
            #$ ansible-playbook 
            #    --skip-tags=SKIP_TAGS
            #    -t TAGS, --tags=TAGS  only run plays and tasks tagged with these values
        


# Otras tareas, que se podrán ejecutar o no, dependiendo si han sido activadas.
# En caso de que un handler sea activado(notify), 
# su ejecución es postpuesta hasta el final de las tareas del bloque (pretasks, tasks, posttasks)
# desde el que se hizo el notify.

    handlers:
        
        -   name: Tarea A - PARADA DEL SISTEMA
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Parada del sistema
            listen: CAMBIO-CONFIGURACION # Le asociamos un evento 
                
        -   name: Tarea B - REINICIO DEL SISTEMA
            debug: # Este módulo lo único que hace es sacar un triste mensaje por pantalla.
                msg: Reinicio el sistema
            listen: CAMBIO-CONFIGURACION 

        